# Generated by Django 3.2.6 on 2021-08-19 02:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='DOB',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
